//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moggle.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lists {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lists() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moggle.Tests.Lists", typeof(Lists).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ant
        ///Bear
        ///Bee
        ///Bird
        ///Butterfly
        ///Camel
        ///Cat
        ///Caterpillar
        ///Chicken
        ///Cow
        ///Crab
        ///Crocodile
        ///Deer
        ///Dog
        ///Dolphin
        ///Donkey
        ///Duck
        ///Elephant
        ///Fish
        ///Frog
        ///Giraffe
        ///Goat
        ///Hamster
        ///Hedgehog
        ///Horse
        ///Jellyfish
        ///Ladybird
        ///Sheep
        ///Lion
        ///Mole
        ///Monkey
        ///Mouse
        ///Octopus
        ///Owl
        ///Panda
        ///Penguin
        ///Pig
        ///Pony
        ///Rabbit
        ///Seahorse
        ///Snake
        ///Spider
        ///Starfish
        ///Stingray
        ///Tiger
        ///Turkey
        ///Turtle
        ///Unicorn
        ///Whale
        ///Worm
        ///Zebra
        ///Pigeon
        ///Dinosaur
        ///Dragon
        ///Kangaroo
        ///Clownfish
        ///Rhinoceros
        ///Toad
        ///Puppy
        ///Hippo
        ///Rat
        ///Ostrich
        ///Peacock
        ///.
        /// </summary>
        internal static string Animals {
            get {
                return ResourceManager.GetString("Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White
        ///Yellow
        ///Blue
        ///Red
        ///Green
        ///Black
        ///Brown
        ///Azure
        ///Ivory
        ///Teal
        ///Silver
        ///Purple
        ///Gray
        ///Orange
        ///Maroon
        ///Charcoal
        ///Aquamarine
        ///Coral
        ///Fuchsia
        ///Wheat
        ///Lime
        ///Crimson
        ///Khaki
        ///pink
        ///Magenta
        ///Gold
        ///Plum
        ///Olive
        ///Cyan
        ///.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria
        ///Italy
        ///Belgium
        ///Latvia
        ///Bulgaria
        ///Lithuania
        ///Croatia
        ///Luxembourg
        ///Cyprus
        ///Malta
        ///Czechia
        ///Netherlands
        ///Denmark
        ///Poland
        ///Estonia
        ///Portugal
        ///Finland
        ///Romania
        ///France
        ///Slovakia
        ///Germany
        ///Slovenia
        ///Greece
        ///Spain
        ///Hungary
        ///Sweden
        ///Ireland
        ///.
        /// </summary>
        internal static string EuCountries {
            get {
                return ResourceManager.GetString("EuCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office worker
        ///Computer programmer
        ///Veterinarian
        ///Street vendor
        ///Factory worker
        ///Miner
        ///Teacher
        ///Real estate agent
        ///Bellboy
        ///Gas station attendant
        ///Speaker
        ///Delivery man
        ///Butcher
        ///Pharmacist
        ///Receptionist
        ///Politician
        ///Tour guide
        ///Entrepreneur
        ///Ballet dancer
        ///Astronaut
        ///Judge
        ///Customs officer
        ///Lawyer
        ///Cashier
        ///Taxi driver
        ///Plumber
        ///Musician
        ///Chef
        ///Baker
        ///Artist
        ///Actor
        ///Actress
        ///Bartender
        ///Hairdresser
        ///Bishop
        ///Optician
        ///Florist
        ///Tailor
        ///Seamstress
        ///Writer
        ///author
        ///Caretaker
        ///Bus driver
        ///Accountant
        ///.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apron
        ///Bread basket
        ///Bowl
        ///Teapot
        ///Measuring cup
        ///Baking tray
        ///Timer
        ///Spice container
        ///Chopping board
        ///Grater
        ///Pie plate
        ///Salad spinner
        ///Colander
        ///Butter dish
        ///Oven glove
        ///Napkin
        ///Chopsticks
        ///Rolling pin
        ///Measuring spoon
        ///Whisk
        ///Wooden spoon
        ///Strainer
        ///Steak hammer
        ///Spoon
        ///Spatula
        ///Mesh skimmer
        ///Cleaver
        ///Ladle
        ///Knife
        ///Kitchen shears
        ///Fork
        ///Cutlery
        ///Corkscrew
        ///Cake slice
        ///Saucepan
        ///pot
        ///Frying pan
        ///Pressure cooker
        ///Cooker
        ///Casserole dish
        ///.
        /// </summary>
        internal static string Kitchen {
            get {
                return ResourceManager.GetString("Kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one
        ///two
        ///three
        ///four
        ///five
        ///six
        ///seven
        ///eight
        ///nine
        ///ten
        ///eleven
        ///twelve
        ///thirteen
        ///fourteen
        ///fifteen
        ///sixteen
        ///seventeen
        ///eigteen
        ///nineteen
        ///twenty
        ///thirty
        ///forty
        ///fifty
        ///sixty
        ///seventy
        ///eighty
        ///ninety
        ///hundred
        ///thousand
        ///million
        ///billion
        ///trillion
        ///half
        ///third
        ///quarter
        ///fifth
        ///.
        /// </summary>
        internal static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrobatics
        ///Aerobic Gymnastics
        ///Archery
        ///Arnis
        ///Artistic Gymnastics
        ///Artistic Swimming
        ///Badminton
        ///Baseball
        ///Basketball
        ///Baton Twirling
        ///Bicycle Motocross
        ///Bobsleigh
        ///Bodybuilding
        ///Bowling
        ///Boxing
        ///Canoeing
        ///Car Racing
        ///Cheerleading
        ///Chess
        ///Cricket
        ///Croquet
        ///Curling
        ///Dance Sport
        ///Darts
        ///Diving
        ///Dodgeball
        ///Fencing
        ///Figure Skating
        ///Football
        ///Soccer
        ///Frisbee
        ///Golf
        ///Handball
        ///Hang Gliding
        ///Hockey
        ///Horseback Riding
        ///Horse Racing
        ///Ice Hockey
        ///Ice Skating
        ///Jet Ski Racing
        ///Judo
        ///Karate
        ///Kayaking
        ///Kendo
        ///Kick Boxing [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alabama
        ///Alaska
        ///Arizona
        ///Arkansas
        ///California
        ///Colorado
        ///Connecticut
        ///Delaware
        ///Florida
        ///Georgia
        ///Hawaii
        ///Idaho
        ///Illinois
        ///Indiana
        ///Iowa
        ///Kansas
        ///Kentucky
        ///Louisiana
        ///Maine
        ///Maryland
        ///Massachusetts
        ///Michigan
        ///Minnesota
        ///Mississippi
        ///Missouri
        ///Montana
        ///Nebraska
        ///Nevada
        ///New Hampshire
        ///New Jersey
        ///New Mexico
        ///New York
        ///North Carolina
        ///North Dakota
        ///Ohio
        ///Oklahoma
        ///Oregon
        ///Pennsylvania
        ///Rhode Island
        ///South Carolina
        ///South Dakota
        ///Tennessee
        ///Texas
        ///Utah
        ///Vermont
        ///Virginia
        ///Washington
        ///West Virginia
        ///Wisconsin        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artichoke
        ///aubergine
        ///eggplant
        ///asparagus
        ///legumes
        ///alfalfa
        ///azuki
        ///bean
        ///sprout
        ///pea
        ///borlotti
        ///broad beans
        ///chickpea
        ///lentil
        ///peanut
        ///soy
        ///mangetout
        ///broccoli
        ///cabbage
        ///kohlrabi
        ///cauliflower
        ///celery
        ///endive
        ///fiddleheads
        ///frisee
        ///fennel
        ///bokchoy
        ///chard
        ///collard
        ///kale
        ///mustard
        ///spinach
        ///anise
        ///basil
        ///caraway
        ///coriander
        ///chamomile
        ///daikon
        ///fennel
        ///lavender
        ///lemongrass
        ///marjoram
        ///oregano
        ///parsley
        ///rosemary
        ///thyme
        ///lettuce
        ///arugula
        ///mushroom
        ///nettle
        ///okra
        ///onion
        ///chive
        ///garlic
        ///leek
        ///onion
        ///shallot
        ///scallion
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vegetables {
            get {
                return ResourceManager.GetString("Vegetables", resourceCulture);
            }
        }
    }
}
