//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moggle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoodGames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoodGames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moggle.GoodGames", typeof(GoodGames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5+216-9-3
        ///7*3412++8
        ///8+732-156
        ///657+3-943
        ///-9+1-7353
        ///2-98366+5
        ///-2317+76+
        ///*5672+-94
        ///397+4-117
        ///833+8-196
        ///--7352-9+
        ///*2942-+76
        ///6912-7+55
        ///6+43271-3
        ///621+-1894
        ///985+1-324
        ///1++3277-9
        ///41-6536+7
        ///318-9+621
        ///534-1+892
        ///2-71213+8
        ///-4571++26
        ///++34972-1
        ///5+44361-4
        ///546-2+98+
        ///391+356-2
        ///+349812+-
        ///527+-1385
        ///8410+-695
        ///136-4+854
        ///249-*31+7
        ///-652476+8
        ///3-3419+*2
        ///4-96247+-
        ///74*+-2653
        ///0+61392-3
        ///27+-8342*
        ///+862179-6
        ///36+2356-1
        ///6+815322-
        ///6+52718+-
        ///-541628+3
        ///2+4537*+1
        ///51763-8+9
        ///15++13-46
        ///1+4613-+8
        ///38+*61 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Century {
            get {
                return ResourceManager.GetString("Century", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stomached
        ///mutual
        ///manse
        ///rabidness
        ///bordered
        ///odder
        ///framework
        ///enclosure
        ///baldrics
        ///taxon
        ///height
        ///altruistic
        ///disputing
        ///neurology
        ///professionalisms
        ///tomfooleries
        ///coddled
        ///configuration
        ///strikebreaker
        ///heartbeats
        ///dreadnoughts
        ///skippers
        ///southward
        ///execrations
        ///spectrometers
        ///victuals
        ///firework
        ///postilion
        ///reconsidered
        ///blvd
        ///subtropics
        ///reequips
        ///woodlands
        ///delightedly
        ///dipsomaniac
        ///fishily
        ///holier
        ///psoriasis
        ///pogroms
        ///vocalist
        ///dipsos
        ///sheetlike
        ///shipbuildings
        ///soundtracks
        ///twang
        ///weighbridge
        ///federal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoodSeeds {
            get {
                return ResourceManager.GetString("GoodSeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LXV-IICX+
        ///I+IXIIX*V
        ///VII*I+XXI
        ///VII+*IXIX
        ///VICX-IXL+
        ///IIXI*IV+X
        ///XI+*VIXII
        ///IIXIXVL-C
        ///XIII*IV+X
        ///V+XI*IXII
        ///ICVI-XLXI
        ///XIXI*+IIV
        ///II+IVIX*X
        ///IIVI*+XIX
        ///VIX+*IXII
        ///X+VIIIX*I
        ///X*IIVIC-I
        ///XIX*I+IIV
        ///IICX-+VXL
        ///XVCX-ILIV
        ///.
        /// </summary>
        internal static string Roman {
            get {
                return ResourceManager.GetString("Roman", resourceCulture);
            }
        }
    }
}
