//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Words {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Words.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET UTF-8
        ///TRY esianrtolcdugmphbyfvkwzESIANRTOLCDUGMPHBYFVKWZ&apos;
        ///ICONV 1
        ///ICONV ’ &apos;
        ///NOSUGGEST !
        ///
        ///# ordinal numbers
        ///COMPOUNDMIN 1
        ///# only in compounds: 1th, 2th, 3th
        ///ONLYINCOMPOUND c
        ///# compound rules:
        ///# 1. [0-9]*1[0-9]th (10th, 11th, 12th, 56714th, etc.)
        ///# 2. [0-9]*[02-9](1st|2nd|3rd|[4-9]th) (21st, 22nd, 123rd, 1234th, etc.)
        ///COMPOUNDRULE 2
        ///COMPOUNDRULE n*1t
        ///COMPOUNDRULE n*mp
        ///WORDCHARS 0123456789
        ///
        ///PFX A Y 1
        ///PFX A   0     re         .
        ///
        ///PFX I Y 1
        ///PFX I   0     in         .
        ///
        ///PFX U Y 1
        ///PFX U   0     un         .
        ///
        ///PFX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index_aff {
            get {
                return ResourceManager.GetString("index_aff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49486
        ///0/nm
        ///0th/pt
        ///1/n1
        ///1st/p
        ///1th/tc
        ///2/nm
        ///2nd/p
        ///2th/tc
        ///3/nm
        ///3rd/p
        ///3th/tc
        ///4/nm
        ///4th/pt
        ///5/nm
        ///5th/pt
        ///6/nm
        ///6th/pt
        ///7/nm
        ///7th/pt
        ///8/nm
        ///8th/pt
        ///9/nm
        ///9th/pt
        ///A/SM
        ///AA/M
        ///AAA
        ///AB/M
        ///ABA
        ///ABC/SM
        ///ABM/SM
        ///ABS
        ///AC/M
        ///ACLU/M
        ///ACT
        ///ACTH/M
        ///AD/M
        ///ADC
        ///ADD
        ///ADM
        ///ADP/M
        ///AF
        ///AFAIK
        ///AFB
        ///AFC/M
        ///AFDC
        ///AFN
        ///AFT
        ///AI/SM
        ///AIDS/M
        ///AK
        ///AL
        ///AM/M
        ///AMA
        ///AMD/M
        ///ANSI/S
        ///ANZUS/M
        ///AOL/M
        ///AP/M
        ///APB
        ///APC
        ///API
        ///APO
        ///APR
        ///AR
        ///ARC
        ///ASAP
        ///ASCII/SM
        ///ASL/M
        ///ASPCA
        ///ATM/M
        ///ATP/M
        ///ATV
        ///AV
        ///AVI
        ///AWACS/M
        ///AWOL/M
        ///AWS/M
        ///AZ/M
        ///AZT/M
        ///Aachen/M
        ///Aaliyah/M
        ///Aaron/M
        ///Abbas/M
        ///Abbasid/M
        ///Abbott/M
        ///Abby/M
        ///Abdul/M
        ///Abe/M
        ///Abel/M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index1 {
            get {
                return ResourceManager.GetString("index1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///be
        ///and
        ///of
        ///a
        ///in
        ///to
        ///have
        ///to
        ///it
        ///I
        ///that
        ///for
        ///you
        ///he
        ///with
        ///on
        ///do
        ///say
        ///this
        ///they
        ///at
        ///but
        ///we
        ///his
        ///from
        ///that
        ///not
        ///n&apos;t
        ///by
        ///she
        ///or
        ///as
        ///what
        ///go
        ///their
        ///can
        ///who
        ///get
        ///if
        ///would
        ///her
        ///all
        ///my
        ///make
        ///about
        ///know
        ///will
        ///as
        ///up
        ///one
        ///time
        ///there
        ///year
        ///so
        ///think
        ///when
        ///which
        ///them
        ///some
        ///me
        ///people
        ///take
        ///out
        ///into
        ///just
        ///see
        ///him
        ///your
        ///come
        ///could
        ///now
        ///than
        ///like
        ///other
        ///how
        ///then
        ///its
        ///our
        ///two
        ///more
        ///these
        ///want
        ///way
        ///look
        ///first
        ///also
        ///new
        ///because
        ///day
        ///more
        ///use
        ///no
        ///man
        ///find
        ///here
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MostCommonWords {
            get {
                return ResourceManager.GetString("MostCommonWords", resourceCulture);
            }
        }
    }
}
